### PR TITLE
TEVA-3304 Job alert form tweaks

### PR DESCRIPTION
**Pull request by elliotcm**
## Jira ticket URL

https://dfedigital.atlassian.net/browse/TEVA-3304

### Before

Screenshot 2021-11-18 at 15 07 21
Screenshot 2021-11-18 at 15 07 26

### After

Screenshot 2021-11-18 at 15 22 51
Screenshot 2021-11-18 at 14 59 43
Screenshot 2021-11-18 at 14 59 47

### CODE REVIEW

**Review by cesidio — APPROVED** [review]

**Comment by david-mears-dfe** [comment]
I initially picked up this ticket and then put it down again. Got some further clarifications from @ife-dev1 on a few queries:

https://ukgovernmentdfe.slack.com/archives/CG9A8H1HP/p1635840002031100

**Comment by elliotcm** [comment]
@david-mears-dfe 
> I initially picked up this ticket and then put it down again. Got some further clarifications from @ife-dev1 on a few queries:
> 
> https://ukgovernmentdfe.slack.com/archives/CG9A8H1HP/p1635840002031100

We should really make sure things like this go into the ticket.

**Comment by david-mears-dfe** [comment]
> We should really make sure things like this go into the ticket.

Definitely. It's unusual for me to pick up and put down a ticket, but it should have gone in.

**Comment by elliotcm** [comment]
@bencmitchell @ife-dev1 

Further changes:

Screenshot 2021-11-19 at 16 16 23
Screenshot 2021-11-19 at 16 00 25

Search remains as before:

Screenshot 2021-11-19 at 16 16 33

**Pull request merged**
