### PR TITLE
Add azure credentials to delete review app workflow

### PR DESCRIPTION
**Pull request by bj2k61**
## Trello card URL

https://trello.com/c/fVBiyDuu

## Changes in this PR:
Add azure account to  delete review app workflow  to facilitate connection from Gitup Action to AKS

## How to review  this PR:
Check the delete  review App workflow 
https://github.com/DFE-Digital/teaching-vacancies/actions/runs/6083391773

### CODE REVIEW

**Review by scruti — APPROVED** [review]

**Comment by bj2k61** [comment]
Closing for testing the  delete review app workflow

**Comment by bj2k61** [comment]
Add environment variable to job

**Comment by bj2k61** [comment]
closing to run destroy

**Comment by bj2k61** [comment]
testing new logic

**Comment by bj2k61** [comment]
test the new logic

**Comment by bj2k61** [comment]
update azure creds

**Pull request merged**
