### PR TITLE
Add location polygon usage counter

### PR DESCRIPTION
**Pull request by david-mears-dfe**
This is to help us to detect when there is something wrong with
our polygons. If a polygon is never or very rarely used - which
here means 'searched in' - then one possible explanation is that
it is misnamed. For example, we map 'herefordshire' to our polygon
called 'herefordshire, county of' because no human would ever
choose to input the latter when they mean 'herefordshire'.

To find issues it might be clever to compare the analytics of
which location search terms are commonly used (currently available
on our [dashboard](https://datastudio.google.com/u/1/reporting/1X_lrbWUn7Nw5LZnRWynJKtalYg6-L4Oi/page/vo6kB) page 30) and the actual recorded usage of the
corresponding location polygon.

### CODE REVIEW

**Review by cpjmcquillan — COMMENTED** [review]
If we export the table to big query, can this analytics information be aggregated by the logs instead? It feels a bit strange to add a column to a table that doesn't serve any other purpose. What does everybody else think? @cesidio @csutter @stevenleggdfe

**Comment by david-mears-dfe** [comment]
> If we export the table to big query, can this analytics information be aggregated by the logs instead? It feels a bit strange to add a column to a table that doesn't serve any other purpose. What do other people think? @cesidio @csutter @stevenleggdfe

Do you mean something like tell Rails to log each time a polygon is used, and then tell Performance Analysis to look for the log output?

**Comment by cpjmcquillan** [comment]
> > If we export the table to big query, can this analytics information be aggregated by the logs instead? It feels a bit strange to add a column to a table that doesn't serve any other purpose. What do other people think? @cesidio @csutter @stevenleggdfe
> 
> Do you mean something like tell Rails to log each time a polygon is used, and then tell Performance Analysis to look for the log output? @cpjmcquillan

That, or infer it by comparing existing search logs with the polygon table and any mappings that take place

**Comment by david-mears-dfe** [comment]
> That, or infer it by comparing existing search logs with the polygon table and any mappings that take place

If I understand this option, it means the monitoring would have to reimplement all the code it is attempting to test. With the coming tranch of location search bug tickets, this mapping might have several components. So to trust the numbers, I would want to either merge this PR, or:

> tell Rails to log each time a polygon is used, and then tell Performance Analysis to look for the log output

**Comment by csutter** [comment]
Just looking through this – do you reckon the triggering an event for location polygon usage using the soon-to-be-merged-I-swear events functionality in #2492 would be a good approach for this?

**Comment by stevenleggdfe** [comment]
> Just looking through this – do you reckon the triggering an event for location polygon usage using the soon-to-be-merged-I-swear events functionality in #2492 would be a good approach for this?

Yes, but I think we might thank ourselves if we come up with a more abstract approach that picks up other things that happen at the same time in the event. Is the event in question viewing a page of site search results? If so we could come up with a site search results event data model that stores polygon information as well as a load of other stuff we'll want to know at the same time.

**Comment by david-mears-dfe** [comment]
> Yes, but I think we might thank ourselves if we come up with a more abstract approach that picks up other things that happen at the same time in the event. Is the event in question viewing a page of site search results? If so we could come up with a site search results event data model that stores polygon information as well as a load of other stuff we'll want to know at the same time.

I think for the original purpose of this PR, what you're talking about (a request) should be considered a separate event (a RequestEvent in #2492's terminology) from what I want to track (a basic back-end Event). These events are related but importantly distinct. We want/need to know how often a location polygon object has in fact been used (which is distinct from how often a polygon ought to have been used), in order to pinpoint issues in our mapping from search parameters to polygon objects.

Let's create a ticket for the request event. I'll update this PR to consume #2492 code once that is merged.

**Comment by david-mears-dfe** [comment]
Ticket: https://dfedigital.atlassian.net/browse/TEVA-1709

**Pull request closed without merging**
