### PR TITLE
[TEVA-1661] Review apps - make PR comment sticky

### PR DESCRIPTION
**Pull request by nickromneydfe**
## Jira ticket URL

https://dfedigital.atlassian.net/browse/TEVA-1661

## Changes in this PR:

- Change the `Post PR comment` action in the review workflow to use [sticky PR comment](https://github.com/marketplace/actions/sticky-pull-request-comment) to ensure the PR conversation only has a single link to the review app

### CODE REVIEW

**Review by csutter — APPROVED** [review]
😍

**Review by cpjmcquillan — APPROVED** [review]

**Comment by martin-bangoura** [comment]
Review app deployed to <https://teaching-vacancies-review-pr-2516.london.cloudapps.digital>

**Comment by david-mears-dfe** [comment]
😍

**Comment by csutter** [comment]
Good old Martin!

**Pull request merged**
