### PR TITLE
Only use Rails subgems we actually need

### PR DESCRIPTION
**Pull request by csutter**
This came out of a subgem of Rails (`activestorage`) using a dependency
that was yanked, blocking us from bundling our dependencies. It should
make our app leaner and reduce the surface area of these sorts of things
happening a tiny bit.

We still need to do something about `govuk-date-fields` because that is
still pulling in _all_ of Rails, but this is a first step.

- Split out individual gems in Gemfile
- Update `govuk-components` to new version that doesn't depend on all of
  Rails
- Update `mimemagic` to new version
- Update Dockerfile to install `shared-mime-info` (new `mimemagic`
  runtime dependency)

### CODE REVIEW

**Comment by cpjmcquillan** [comment]
Are we even using `gov-uk-date-fields` at all?

**Comment by csutter** [comment]
> Are we even using gov-uk-date-fields at all?
Sadly yes, although my thinking is we should get rid of them as the form builder supports date fields anyway 🤷‍♀️ 

We just probably never got around to it?

**Comment by cpjmcquillan** [comment]
> > Are we even using gov-uk-date-fields at all?
> > Sadly yes, although my thinking is we should get rid of them as the form builder supports date fields anyway 🤷‍♀️
> 
> We just probably never got around to it?

Ah ok I can see it now. Yeah let's get rid ASAP

**Comment by martin-bangoura** [comment]
Review app deployed to <https://teaching-vacancies-review-pr-3166.london.cloudapps.digital>

**Review by felixtheflex — APPROVED** [review]

**Pull request merged**
