### PR TITLE
[TEVA-2435] Extend redirect when job application exists to all non-draft statuses

### PR DESCRIPTION
**Pull request by cpjmcquillan**
## Jira ticket
https://dfedigital.atlassian.net/browse/TEVA-2435

## Changes in this PR
- Cannot apply for jobs where there is an existing job application for that job

## Product sign off
- [x] Looks good!

### CODE REVIEW

**Review by cesidio — APPROVED** [review]

**Review by alexbowen — APPROVED** [review]
looks good but is there a spec to update or a gap in testing if there isnt with this slight change in template logic?

**Comment by cpjmcquillan** [comment]
> looks good but is there a spec to update or a gap in testing if there isnt with this slight change in logic? seems like an important thing to test from your PR description

The test was already there, although probably a bit vague for the stricter logic. Now the logic and the test that already exists probably align much better https://github.com/DFE-Digital/teaching-vacancies/blob/e7d8f60f48fba5109b70c2f149cb3df990977f9d/spec/requests/jobseekers/job_applications/build_spec.rb#L62

**Comment by bencmitchell** [comment]
Warning message looks good 
image
However the status on the Job Listing has not updated, it has returned to "Apply for this job" , but when pressed it takes me back to My applications page and tells me I have already applied, link should read "Withdrawn - view application" and take me to view my application instead
image 
image

**Comment by bencmitchell** [comment]
Looks good to me, status updated 
image

**Pull request merged**
