### PR TITLE
[207] Sort profile employments newest to oldest

### PR DESCRIPTION
**Pull request by elliotcm**
### Before
Screenshot 2023-03-15 at 09 01 11

Screenshot 2023-03-15 at 09 00 50

### After
Screenshot 2023-03-15 at 09 03 29

Screenshot 2023-03-15 at 09 03 42

### CODE REVIEW

**Comment by elliotcm** [comment]
[Display Work history roles in chronological order on the Candidate Profile](https://trello.com/c/eBgqY4aI/207-display-work-history-roles-in-chronological-order-on-the-candidate-profile)

**Comment by bencmitchell** [comment]
Hi @elliotcm 
The start date functionality looks to be working perfectly,
The only part missing is that any role that the jobseeker marks as their current role should be displayed at the top of the list (this should take precedence over the start date check)
image

**Comment by elliotcm** [comment]
@bencmitchell Updated

**Comment by bencmitchell** [comment]
Thanks @elliotcm  looks good to me 👍

**Pull request merged**
