### PR TITLE
[TEVA-4002] Button click tracking

### PR DESCRIPTION
**Pull request by elliotcm**
## Jira ticket URL

https://dfedigital.atlassian.net/browse/TEVA-4002

### CODE REVIEW

**Review by csutter — APPROVED** [review]
Looks good – one more thing, do you think it would be worth to have a `subject` for the `copied_to_clipboard` event too? So we could e.g. track the anonymised ID for the vacancy whose URL has been copied.

**Comment by elliotcm** [comment]
> Looks good – one more thing, do you think it would be worth to have a `subject` for the `copied_to_clipboard` event too? So we could e.g. track the anonymised ID for the vacancy whose URL has been copied.

@csutter That sounds like a @stevenleggdfe question.

**Comment by stevenleggdfe** [comment]
> > Looks good – one more thing, do you think it would be worth to have a `subject` for the `copied_to_clipboard` event too? So we could e.g. track the anonymised ID for the vacancy whose URL has been copied.
> 
> @csutter That sounds like a @stevenleggdfe question.

Yes please @elliotcm !

**Comment by elliotcm** [comment]
@csutter @stevenleggdfe Done!

**Review by csutter — APPROVED** [review]

**Pull request merged**
