### PR TITLE
Change apostrophes into quotes

### PR DESCRIPTION
**Pull request by david-mears-dfe**
This changes straight apostrophes into curly quotes, as in the
below screenshot of already-existing curly quotes, only when
the context requires quotes (leaving apostrophes as they are).

curlies

### CODE REVIEW

**Comment by martin-bangoura** [comment]
Review app deployed to <https://teaching-vacancies-review-pr-2999.london.cloudapps.digital>

**Comment by alexbowen** [comment]
i think should use :before and :after CSS pseudoclasses for this

**Review by alexbowen — APPROVED** [review]

**Comment by cpjmcquillan** [comment]
Commit `6c4af82` looks a bit suspicious - what's it for?

**Comment by david-mears-dfe** [comment]
> Commit `6c4af82` looks a bit suspicious - what's it for?

It merges a change that was in master - had to update this branch.

**Pull request merged**
