### PR TITLE
[182] Properly humanize job preferences on search index

### PR DESCRIPTION
**Pull request by elliotcm**
### Before
Screenshot 2023-03-15 at 08 44 33

### After
Screenshot 2023-03-15 at 08 45 36

### CODE REVIEW

**Comment by elliotcm** [comment]
[Implement human readable text on the Candidate Profiles page](https://trello.com/c/duknnkaq/182-implement-human-readable-text-on-the-candidate-profiles-page)

**Comment by bencmitchell** [comment]
Hi @elliotcm , are you able to turn on a jobseeker profile in this review app please?

**Comment by elliotcm** [comment]
@bencmitchell Done

**Comment by bencmitchell** [comment]
Thanks @elliotcm , looks good to me.

**Pull request merged**
