### PR TITLE
[110] Allow turning jobseeker profiles on and off

### PR DESCRIPTION
**Pull request by elliotcm**
## Screenshots of UI changes:

Screenshot 2023-03-13 at 11 31 39
Screenshot 2023-03-13 at 11 31 43
Screenshot 2023-03-13 at 11 39 40
Screenshot 2023-03-13 at 11 41 53
Screenshot 2023-03-13 at 11 42 00
Screenshot 2023-03-13 at 11 42 08
Screenshot 2023-03-13 at 11 42 17

### CODE REVIEW

**Comment by bencmitchell** [comment]
Hi @elliotcm 
A few small content tweaks on the Candidate side.

- A small comment on the copy on the confirmation page to turn on the profile.

This should read "When you turn on your profile it will be visible to hiring staff, and they can invite you to apply for roles"
image

- This got a little lost in the updated designs so if this makes more sense putting in a small follow up ticket let me know, but when the profile is in the On state, we need to show "Turn off profile" and "Preview profile" as links beneath the Your Profile heading. 

image

- Also, when the profile is turned on, the section heading at the bottom should be "Preview and turn off profile" 

image

Otherwise this is looking good to me.

**Comment by bencmitchell** [comment]
[Candidates can turn their profile on and off](https://trello.com/c/HwDX4cPY/110-candidates-can-turn-their-profile-on-and-off)

**Comment by elliotcm** [comment]
@bencmitchell Thanks for the review.  I've updated per your feedback, redeploying shortly.

**Comment by bencmitchell** [comment]
Thanks @elliotcm, changes look good.
Sorry for not flagging this at the same time, has just come to me looking at the new links in the review app.
Similar to the "Turn off profile" and "Preview profile" links at the top of the page when the profile is turned on, when the profile is turned off can we show "Turn on profile" and "Preview profile" links please?

**Comment by elliotcm** [comment]
> Thanks @elliotcm, changes look good. Sorry for not flagging this at the same time, has just come to me looking at the new links in the review app. Similar to the "Turn off profile" and "Preview profile" links at the top of the page when the profile is turned on, when the profile is turned off can we show "Turn on profile" and "Preview profile" links please?

@bencmitchell Done

**Comment by bencmitchell** [comment]
Thanks @elliotcm, looks good to me 👍

**Pull request merged**
