### PR TITLE
[TEVA-3991] Rework the homepage SEO / landing page links

### PR DESCRIPTION
**Pull request by elliotcm**
## Jira ticket URL

https://dfedigital.atlassian.net/browse/TEVA-3991

### Before

Screenshot 2022-03-29 at 10 05 00

#### Closed
Screenshot 2022-03-29 at 13 44 53

#### Open
Screenshot 2022-03-29 at 13 45 55

### CODE REVIEW

**Comment by alexbowen** [comment]
Screenshot 2022-03-29 at 15 02 23

this gap seems quite big, and is more apparent on mobile

**Comment by alexbowen** [comment]
is this supposed to have the behaviour that the open/closed state of each area is 'remebered' - i presume with browser session/local storage?

**Review by csutter — APPROVED** [review]
See Alex's visual comments, and there's some stray commented out subjects, other than that 👍

**Comment by elliotcm** [comment]
> there's some stray commented out subjects, other than that 👍

@csutter Oops, fixed.

**Comment by elliotcm** [comment]
> is this supposed to have the behaviour that the open/closed state of each area is 'remebered' - i presume with browser session/local storage?

@alexbowen I wondered about both of those, but that all comes from the govuk component and it seemed best to use those standards
https://govuk-components.netlify.app/components/accordion/

**Comment by elliotcm** [comment]
Product signoff from @dannychadburndfe 
https://ukgovernmentdfe.slack.com/archives/CG9A8H1HP/p1648559534815079

**Pull request merged**
